# Generated by Django 5.2.3 on 2025-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrequest',
            name='resume',
            field=models.URLField(),
        ),
    ]
