# Generated by Django 5.2.3 on 2025-07-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_vacancypost_compliance_rating_and_more'),
        ('studentapp', '0007_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articleapp.vacancypost'),
        ),
    ]
