# Generated by Django 5.2.3 on 2025-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_vacancypost_share_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancypost',
            name='compliance_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='consultancy_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='direct_tax_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='gst_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='internal_audit_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='other_specialisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='other_specialisation_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancypost',
            name='statutory_audit_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
